const PDFDocument = require('pdfkit');

function generatePDF(analysis, chatType) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const buffers = [];

    doc.on('data', chunk => buffers.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(buffers)));
    doc.on('error', reject);

    if (chatType === 'individual') {
      buildCouplePDF(doc, analysis);
    } else {
      buildGroupPDF(doc, analysis);
    }

    doc.end();
  });
}

function buildCouplePDF(doc, a) {
  const pink = '#E91E8C';
  const purple = '#7B2D8B';
  const dark = '#1a1a2e';
  const light = '#fff5f9';

  // Header
  doc.rect(0, 0, doc.page.width, 120).fill(purple);
  doc.fontSize(32).fillColor('#ffffff').font('Helvetica-Bold')
     .text('💞 Your Love Story in Numbers', 50, 30, { align: 'center' });
  doc.fontSize(13).fillColor('#ffd6ec')
     .text(`${(a.participants || ['You', 'Them']).join(' & ')} · ${a.dateRange?.from || ''} – ${a.dateRange?.to || ''}`, 50, 75, { align: 'center' });

  doc.moveDown(2);

  // Summary
  section(doc, '✨ Your Story', pink);
  doc.fontSize(12).fillColor(dark).font('Helvetica')
     .text(a.summary || 'A beautiful connection.', { lineGap: 4 });

  doc.moveDown(1);

  // Love Metrics big stats
  section(doc, '💕 Love Metrics', pink);
  const love = a.loveMetrics || {};
  bigStat(doc, '❤️ Times "I Love You" was said', love.iLoveYouCount || 0, pink);
  bigStat(doc, '💌 Total Love Expressions', love.totalLoveExpressions || 0, pink);
  if (love.mostRomanticDay) {
    doc.fontSize(11).fillColor(dark).text(`🌹 Most Romantic Day: ${love.mostRomanticDay}`).moveDown(0.3);
  }
  if (love.mostRomanticMessage) {
    doc.fontSize(11).fillColor(purple).font('Helvetica-Oblique')
       .text(`"${love.mostRomanticMessage}"`, { lineGap: 3 }).moveDown(0.5);
  }

  // Message Stats
  section(doc, '📊 Message Stats', pink);
  const ms = a.messageStats || {};
  kvLine(doc, '💬 Total Messages', a.totalMessages);
  kvLine(doc, '📱 Who texts more', ms.whoTextsMore);
  kvLine(doc, '📝 Who sends longer messages', ms.whoSendsLongerMessages);
  if (ms.person1) kvLine(doc, `${ms.person1.name} sent`, `${ms.person1.messageCount} messages`);
  if (ms.person2) kvLine(doc, `${ms.person2.name} sent`, `${ms.person2.messageCount} messages`);

  doc.moveDown(0.5);

  // Top Words
  if (a.topWords?.length) {
    section(doc, '🔤 Your Most Used Words', pink);
    const wordLine = a.topWords.slice(0, 10)
      .map(w => `${w.word} (${w.count}x)${w.meaning ? ' — '+w.meaning : ''}`)
      .join('   ·   ');
    doc.fontSize(11).fillColor(dark).font('Helvetica').text(wordLine, { lineGap: 4 });
    doc.moveDown(0.5);
  }

  // Top Emojis
  if (a.topEmojis?.length) {
    section(doc, '😍 Your Favourite Emojis', pink);
    const emojiLine = a.topEmojis.slice(0, 8).map(e => `${e.emoji} ×${e.count}`).join('   ');
    doc.fontSize(14).fillColor(dark).text(emojiLine, { lineGap: 4 });
    doc.moveDown(0.5);
  }

  // Timing
  section(doc, '⏰ When You Talk', pink);
  kvLine(doc, '🌙 Most active hour', a.peakHour);
  kvLine(doc, '📅 Most active day', a.peakDay);

  // Vibe Score
  doc.moveDown(0.5);
  section(doc, '💫 Vibe Score', pink);
  doc.fontSize(36).fillColor(pink).font('Helvetica-Bold')
     .text(`${a.vibeScore || '?'}/100`, { align: 'center' });
  doc.fontSize(16).fillColor(purple)
     .text(a.vibeLabel || '', { align: 'center' });
  doc.moveDown(0.5);
  doc.fontSize(12).fillColor(dark).font('Helvetica')
     .text(a.compatibilityNote || '', { align: 'center', lineGap: 4 });

  // Fun Facts
  if (a.funFacts?.length) {
    doc.addPage();
    section(doc, '🎉 Fun Facts About You Two', pink);
    a.funFacts.forEach((fact, i) => {
      doc.fontSize(12).fillColor(dark).font('Helvetica')
         .text(`${i + 1}. ${fact}`, { lineGap: 5 });
    });
    doc.moveDown(0.5);
  }

  // Milestones
  if (a.milestones?.length) {
    section(doc, '🏅 Milestones', pink);
    a.milestones.forEach(m => {
      doc.fontSize(11).fillColor(purple).font('Helvetica-Bold').text(m.date || '', { continued: true });
      doc.fillColor(dark).font('Helvetica').text(`  ${m.event || ''}`);
    });
    doc.moveDown(0.5);
  }

  // Inside Jokes
  if (a.insideJokes?.length) {
    section(doc, '🤫 Inside Jokes & Phrases', pink);
    doc.fontSize(12).fillColor(dark).font('Helvetica')
       .text(a.insideJokes.join('   ·   '), { lineGap: 4 });
    doc.moveDown(0.5);
  }

  // Footer
  doc.moveDown(2);
  doc.fontSize(9).fillColor('#aaa').font('Helvetica')
     .text('Generated by ChatStory.app · Your data was deleted immediately after this PDF was created. 💜', { align: 'center' });
}

function buildGroupPDF(doc, a) {
  const orange = '#FF6B35';
  const teal = '#00A896';
  const dark = '#1a1a2e';

  // Header
  doc.rect(0, 0, doc.page.width, 120).fill(teal);
  doc.fontSize(28).fillColor('#ffffff').font('Helvetica-Bold')
     .text(`🎉 ${a.groupName || 'Group Chat'} — Wrapped!`, 50, 30, { align: 'center' });
  doc.fontSize(12).fillColor('#d0fff8')
     .text(`${a.totalMembers || '?'} members · ${a.dateRange?.from || ''} – ${a.dateRange?.to || ''}`, 50, 80, { align: 'center' });

  doc.moveDown(2);

  // Summary
  section(doc, '👥 Group Vibe', teal);
  doc.fontSize(12).fillColor(dark).font('Helvetica').text(a.summary || '', { lineGap: 4 });
  doc.moveDown(0.5);
  if (a.groupPersonality) {
    doc.fontSize(12).fillColor(dark).font('Helvetica-Oblique').text(a.groupPersonality, { lineGap: 4 });
  }

  // Chaos Score
  doc.moveDown(0.5);
  section(doc, '🔥 Chaos Score', orange);
  doc.fontSize(36).fillColor(orange).font('Helvetica-Bold')
     .text(`${a.chaosScore || '?'}/100`, { align: 'center' });
  doc.fontSize(16).fillColor(teal).text(a.chaosLabel || '', { align: 'center' });
  doc.moveDown(0.5);

  // Member Leaderboard
  section(doc, '🏆 Member Leaderboard', teal);
  kvLine(doc, '💬 Total Messages', a.totalMessages);
  if (a.members?.length) {
    a.members.slice(0, 10).forEach((m, i) => {
      const bar = '█'.repeat(Math.round((m.percentage || 0) / 5));
      doc.fontSize(11).fillColor(dark).font('Helvetica')
         .text(`${i + 1}. ${m.name}  ${bar}  ${m.messageCount} msgs (${m.percentage}%)  — ${m.title || ''}`, { lineGap: 4 });
    });
  }

  // Fun Titles
  const ft = a.funTitles || {};
  if (Object.keys(ft).length) {
    section(doc, '🎭 Member Awards', orange);
    const titleMap = {
      theChatterbox: '💬 The Chatterbox', theLurker: '🤫 The Lurker',
      theNightOwl: '🌙 The Night Owl', theEarlyBird: '🌅 The Early Bird',
      theEmojiKing: '😂 The Emoji King', thePhilosopher: '🧠 The Philosopher'
    };
    Object.entries(ft).forEach(([key, val]) => {
      if (val) kvLine(doc, titleMap[key] || key, val);
    });
    doc.moveDown(0.5);
  }

  // Awards
  if (a.awards?.length) {
    doc.addPage();
    section(doc, '🏅 Special Awards', orange);
    a.awards.forEach(award => {
      doc.fontSize(13).fillColor(teal).font('Helvetica-Bold').text(award.title || '');
      doc.fontSize(11).fillColor(dark).font('Helvetica')
         .text(`Winner: ${award.winner}  —  ${award.reason}`, { lineGap: 6 });
    });
    doc.moveDown(0.5);
  }

  // Top Words & Emojis
  if (a.topWords?.length) {
    section(doc, '🔤 Most Used Words', teal);
    doc.fontSize(11).fillColor(dark).font('Helvetica')
       .text(a.topWords.slice(0, 10).map(w => `${w.word} (${w.count}x)`).join('   ·   '), { lineGap: 4 });
    doc.moveDown(0.5);
  }

  if (a.topEmojis?.length) {
    section(doc, '😂 Top Emojis', orange);
    doc.fontSize(14).fillColor(dark)
       .text(a.topEmojis.slice(0, 8).map(e => `${e.emoji} ×${e.count}`).join('   '), { lineGap: 4 });
    doc.moveDown(0.5);
  }

  // Timing
  section(doc, '⏰ Activity Patterns', teal);
  kvLine(doc, '🌙 Most active hour', a.peakHour);
  kvLine(doc, '📅 Most active day', a.peakDay);
  kvLine(doc, '🗣️ Person everyone replies to', a.mostReplyTo);

  // Fun Facts
  if (a.funFacts?.length) {
    section(doc, '🎊 Fun Facts', orange);
    a.funFacts.forEach((fact, i) => {
      doc.fontSize(12).fillColor(dark).font('Helvetica').text(`${i + 1}. ${fact}`, { lineGap: 5 });
    });
  }

  // Footer
  doc.moveDown(2);
  doc.fontSize(9).fillColor('#aaa').font('Helvetica')
     .text('Generated by ChatStory.app · All chat data was deleted after PDF creation. 💜', { align: 'center' });
}

// Helpers
function section(doc, title, color) {
  doc.moveDown(0.5);
  doc.fontSize(15).fillColor(color).font('Helvetica-Bold').text(title);
  doc.moveTo(doc.page.margins.left, doc.y + 2)
     .lineTo(doc.page.width - doc.page.margins.right, doc.y + 2)
     .strokeColor(color).lineWidth(1).stroke();
  doc.moveDown(0.4);
}

function kvLine(doc, label, value) {
  if (!value && value !== 0) return;
  doc.fontSize(11).fillColor('#333').font('Helvetica-Bold').text(`${label}: `, { continued: true });
  doc.font('Helvetica').fillColor('#111').text(String(value), { lineGap: 4 });
}

function bigStat(doc, label, value, color) {
  doc.fontSize(11).fillColor('#555').font('Helvetica').text(label);
  doc.fontSize(28).fillColor(color).font('Helvetica-Bold').text(String(value));
  doc.moveDown(0.3);
}

module.exports = { generatePDF };
